config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "pages#home"

  resources :users, only: %i[index]


  get "experiences/:id/like", to: "experiences#like", as: :like_experience

  get "up" => "rails/health#show", as: :rails_health_check

  get "/experiences", to: "experiences#index", as: :experiences

  resources :journeys, only: %i[show new create] do
    resources :experiences, only: %i[new create]
  end

  patch "/journeys/:id/delete_packing_item", to: "journeys#delete_packing_item", as: :delete_packing_item
  # resources :experiences, only: [:show] do
  #   member do
  #     patch "like", to: "experiences#like"
  #   end
  # end

  post "saved_experience/:experience_id", to: "saved_experiences#create", as: :saved_experience

  delete "/saved_experience/:id", to: "saved_experiences#destroy", as: :delete_saved_experience



  resources :chatrooms, only: %i[index show create] do
    resources :messages, only: :create
  end

  get "/:username", to: "users#profile_page", as: :profile_page

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user_1, class_name: "User"
  belongs_to :user_2, class_name: "User"
  # belongs_to :user
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    chatrooms1 = Chatroom.where(user_1_id: current_user)
    chatrooms2 = Chatroom.where(user_2_id: current_user)
    @chatrooms = chatrooms1 + chatrooms2
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def create
    user_2 = User.find_by(username: params[:user_2])
    chatroom = Chatroom.new(user_1: current_user, user_2: user_2)
    if chatroom.save!
      redirect_to chatroom_path(chatroom)
    else
      render 'profile_page', status: :unprocessable_entity
    end
  end
end

app/views/chatrooms/index.html.erb
<div class="container">
  <div class="back-chevron">
    <%= link_to experiences_path do %>
      <i class="fa-solid fa-chevron-left"></i>
    <% end %>
  </div>
  <div class="messages-label">
    <h2>Your messages</h2>
  </div>
  <% @chatrooms.each do |chatroom| %>
    <% if  chatroom.user_1.username == current_user.username%>
      <% user = chatroom.user_2 %>
    <% else %>
      <% user = chatroom.user_1 %>
    <% end %>

    <%= link_to chatroom_path(chatroom), class: "link-to-chat" do %>
      <div class="each-chatroom">
        <%= cl_image_tag user.photo.key %>
        <p><strong><%= user.first_name %></strong></p>
      </div>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<div data-controller="chatroom-subscription"
    data-chatroom-subscription-user-id-value="<%= current_user.id %>"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
  <div class="container chatroom">
    <div class="back-chevron">
      <%= link_to chatrooms_path do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
      <% if @chatroom.user_1 == current_user %>
          <h2><%= @chatroom.user_2.username %></h2>
        <% else %>
          <h2><%= @chatroom.user_1.username %></h2>
        <% end %>
      <div class="img-pos">
        <%= cl_image_tag current_user.photo.key, class: 'chatroom-img' %>
        <% if @chatroom.user_1 == current_user %>
          <%= cl_image_tag @chatroom.user_2.photo.key, class: 'chatroom-img reciever-img' %>
        <% else %>
          <%= cl_image_tag @chatroom.user_1.photo.key, class: 'chatroom-img reciever-img' %>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message, user: message.user %>
      <% end %>
    </div>
  </div>
  <%= simple_form_for [@chatroom, @message],
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "px-4 d-flex align-items-center justify-content-between w-100" }   do |f|
  %>
      <div class="d-flex align-items-center justify-content-between w-100 chatroom-message-style">
        <%= f.input_field :content,
          label: false,
          placeholder: "Message #{ current_user == @chatroom.user_1 ? @chatroom.user_2.username : @chatroom.user_1.username }",
          class: "flex-grow-1 mb-0 message-box form-control"
        %>
        <%= button_tag type: 'submit', class: "btn btn-primary-custom chatroom-send-btn" do %>
          <i class="fa-regular fa-paper-plane"></i>
        <% end %>
      </div>
  <% end %>
</div>