config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "pages#home"

  resources :users, only: %i[index]


  get "experiences/:id/like", to: "experiences#like", as: :like_experience

  get "up" => "rails/health#show", as: :rails_health_check

  get "/experiences", to: "experiences#index", as: :experiences

  resources :journeys, only: %i[show new create] do
    resources :experiences, only: %i[new create]
  end

  patch "/journeys/:id/delete_packing_item", to: "journeys#delete_packing_item", as: :delete_packing_item
  # resources :experiences, only: [:show] do
  #   member do
  #     patch "like", to: "experiences#like"
  #   end
  # end

  post "saved_experience/:experience_id", to: "saved_experiences#create", as: :saved_experience

  delete "/saved_experience/:id", to: "saved_experiences#destroy", as: :delete_saved_experience



  resources :chatrooms, only: %i[index show create] do
    resources :messages, only: :create
  end

  get "/:username", to: "users#profile_page", as: :profile_page

end

app/models/user.rb
class User < ApplicationRecord
  has_many :journeys
  has_one_attached :photo
  has_many :experiences, through: :journeys
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :chatrooms
  validates :username, :email, :password, :first_name, :last_name, :bio, presence: true
  validates :bio, length: { maximum: 100 }
  validates :username, uniqueness: true

  # Password needs to be at least 8 chars long, one special char and one uppper case letter
  validates :password, format: { with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}/ }
  validates :email, uniqueness: true

  acts_as_voter

  include PgSearch::Model
  pg_search_scope :search_by_username,
    against: [ :username ],
    using: {
      tsearch: { prefix: true }
    }
  has_many :chatrooms_as_user_1, class_name: "chatroom", foreign_key: :user_1
  has_many :chatrooms_as_user_2, class_name: "chatroom", foreign_key: :user_2

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile_page
    set_user
    @journeys = @user.journeys
  end

  def index
    if params[:query].present?
      @users = User.search_by_username(params[:query])
    else
      @users = User.all
    end
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/views/users/_message_link.html.erb
<% if Chatroom.where(user_1_id: current_user.id, user_2_id: user.id).empty? && Chatroom.where(user_1_id: user.id, user_2_id: current_user.id).empty? %>
  <%= form_with url: chatrooms_path, method: :post do %>
    <%= hidden_field_tag :user_2, @user.username %>
    <%= button_tag(type: "submit", class: 'btn-primary-custom message-btn') do %>
      <%= image_tag("messages_icon_white.svg") %>
    <% end %>
  <% end %>
<% elsif Chatroom.where(user_1_id: user.id, user_2_id: current_user.id).empty? %>
  <%= form_with url: chatroom_path(Chatroom.where(user_1_id: current_user.id, user_2_id: user.id).first), method: :get do %>
    <%= button_tag(type: "submit", class: 'btn-primary-custom message-btn') do %>
      <%= image_tag("messages_icon_white.svg") %>
    <% end %>
  <% end %>
<% elsif Chatroom.where(user_1_id: current_user.id, user_2_id: user.id).empty? %>
  <%= form_with url: chatroom_path(Chatroom.where(user_1_id: user.id, user_2_id: current_user.id).first), method: :get do %>
    <%= button_tag(type: "submit", class: 'btn-primary-custom message-btn') do %>
      <%= image_tag("messages_icon_white.svg") %>
    <% end %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="row m-1">
    <div class="col-12 my-3">
      <%= render 'shared/search', url: users_path %>
    </div>
</div>

<div class="users-box">
  <% @users.each do |user| %>
    <div class="user-card">
    <%= link_to profile_page_path(user.username) do  %>
      <%= image_tag(user.photo) %>
      <% end %>
      <%= link_to profile_page_path(user.username) do  %>
        <p> <%= user.username %> </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/profile_page.html.erb
<%# PP means profile page haha %>
<div class="backg">
    <div class="orange-top">
    </div>
  <div class="container profile-info-container">
    <div class="avatar-row white-cover">
      <div class="stats-next-to-avatar">
        <h4><%= @user.journeys.count %></h4>
        <h6>Journeys</h6>
      </div>
      <% if @user && @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, alt: "profile-pic", class: "avatar-circle-large profile-page-avatar" %>
          <% else %>
            <%= image_tag("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class: "avatar-circle-large profile-page-avatar") %>
          <% end %>
      <div class="stats-next-to-avatar">
        <h4>
        <% sum = 0 %>
        <% @user.experiences.each do |experience| %>
          <% sum += experience.weighted_total %>
        <% end %>
        <%= number_with_delimiter(sum, :delimiter => ',') %>
        </h4>
        <h6>Likes</h6>
      </div>
    </div>
    <div class="user-name-bio-and-message">
      <div class="username-container">
        <h1 class="user-name">
        <%= @user.username %>
        </h1>
        <% if @user == current_user %>
          <div class="edit-link-container">
            <%= link_to edit_user_registration_path do %>
              <%= image_tag "pencil_icon_grey.svg", class: "edit-pen-icon" %>
            <% end %>
          </div>
        <% end %>
      </div>


      <h6 id="user-bio-margins">
        <%= @user.bio %>
      </h6>
      <% if @user != current_user %>
        <%= render 'message_link', user: @user, class: "message-btn" %>
      <% end %>
    </div>

  </div>

  <hr>

      <ul class="nav nav-pills mb-4 justify-content-evenly" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active user-tabs" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Experiences</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link user-tabs" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Journeys</button>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <%# Experiences %>
          <div class="lower-pp container">
            <div class="row justify-content-center">
                <% @journeys.each do |journey| %>
                  <% journey.experiences.each do |experience| %>
                    <% experience.photos.each do |photo| %>
                      <div class="col-4 p-0 m-2", style="background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.00) 67.71%, #292929 100%), url(<%= cl_image_path photo.key %>);">
                          <h6 class="journey-name"><%= experience.title %></h6>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          <%# Journeys %>
          <div class="lower-pp container">
            <div class="my-grid">
              <% @journeys.each do |journey| %>
                <%= link_to journey_path(journey), class: 'journey-links' do %>
                  <div class="card" style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('<%= image_path unsplash_image_url(size: '300x200', tags: journey.location) %>')">
                      <h4 class="journey-card-name"><%= journey.location %></h4>
                      <h6 class="journey-card-date"><%= journey.start_date.strftime('%d/%m/%y') %></h6>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/users/show.html.erb
<%# PP means profile page haha %>
<div class="backg">
  <div class="container">
    <div class="upper-pp">
      <% if @user && @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, alt: "profile-pic", class: "avatar-circle-large" %>
          <% else %>
            <%= image_tag("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class: "avatar-circle-large") %>
          <% end %>
      <h1>
        <%= @user.first_name %> <%= @user.last_name %>
        <%= link_to edit_user_registration_path do %>
          <i class="fa-solid fa-pen-to-square fa-xs", style="color:Black;" ></i>
        <% end %>
      </h1>
      <h6><%= @user.username %></h6>
      <div class="follow-section">
        <div class="followers"><h4><%= @user.followers %></h4><h6>Followers</h6></div>
        <div class="following"><h4><%= @user.following %></h4><h6>Following</h6></div>
      </div>
      <h6><strong>About me:</strong></h6>
      <p><%= @user.bio %></p>
      <%= render 'message_link', user: @user %>
    </div>
  </div>
  <hr>
  <ul class="nav nav-pills mb-4 justify-content-evenly" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active user-tabs" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Experiences</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link user-tabs" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Journeys</button>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <%# Experiences %>
      <div class="lower-pp container" style="min-height:100vh;">
        <div class="row justify-content-center">
            <% @journeys.each do |journey| %>
              <% journey.experiences.each do |experience| %>
                <% experience.photos.each do |photo| %>
                  <div class="col-4 p-0 mx-2">
                    <%= cl_image_tag photo.key %><%= journey.location %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <%# Journeys %>
      <div class="lower-pp container" style="min-height:100vh;">
        <div class="my-grid">
          <% @journeys.each do |journey| %>
            <%= link_to journey_path(journey), class: 'journey-links' do %>
              <div class="card" style="background-image: url('<%= image_path unsplash_image_url(size: '300x200', tags: journey.location) %>')">
                <%= journey.location %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>