config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "pages#home"

  resources :users, only: %i[index]


  get "experiences/:id/like", to: "experiences#like", as: :like_experience

  get "up" => "rails/health#show", as: :rails_health_check

  get "/experiences", to: "experiences#index", as: :experiences

  resources :journeys, only: %i[show new create] do
    resources :experiences, only: %i[new create]
  end

  patch "/journeys/:id/delete_packing_item", to: "journeys#delete_packing_item", as: :delete_packing_item
  # resources :experiences, only: [:show] do
  #   member do
  #     patch "like", to: "experiences#like"
  #   end
  # end

  post "saved_experience/:experience_id", to: "saved_experiences#create", as: :saved_experience

  delete "/saved_experience/:id", to: "saved_experiences#destroy", as: :delete_saved_experience



  resources :chatrooms, only: %i[index show create] do
    resources :messages, only: :create
  end

  get "/:username", to: "users#profile_page", as: :profile_page

end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :journey

  has_many :saved_experiences, dependent: :destroy
  has_many_attached :photos

  validates :address, :title, :content, :category, presence: true, uniqueness: true
  validates :photos, presence: true
  validates :title, length: { maximum: 25 }
  validates :content, length: { maximum: 50 }
  validates :category, inclusion: { in: ["Food", "Nightlife", "Art and Culture", "Other"] }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  acts_as_votable

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [ :address, :title ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    @saved_experience = SavedExperience.new
    if params[:query].present?
      @experiences = Experience.search_by_address(params[:query])
    else
      @experiences = Experience.all
    end
  end

  def new
    @journey = Journey.find(params[:journey_id])
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @journey = Journey.find(params[:journey_id])
    @experience.journey = @journey
    if @experience.save!
      redirect_to profile_page_path(current_user.username)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def like
    @experience = Experience.find(params[:id])
    if current_user.voted_for? @experience
      @experience.unliked_by current_user
    else
      @experience.liked_by current_user
    end
    respond_to do |format|
      format.html { redirect_to experiences_path }
      format.text { render partial: "experiences/like_link", locals: { experience: @experience }, formats: [:html] }
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:title, :content, :address, :category, :journey, photos: [])
  end
end

app/views/experiences/_like_link.html.erb
<%= content_tag "div", id: "like#{experience.id}" do %>
  <div class="like" data-like-experience-target = "total">
      <%= experience.weighted_score %>
  </div>
  <%= link_to like_experience_path(experience), method: :patch, remote: true do %>
    <% if current_user.voted_for? experience %>
      <i class="fa-solid fa-heart vote-icons" style="color: #FF6900;"></i>
    <% else %>
      <i class="fa-solid fa-heart vote-icons" style="color: rgba(239, 239, 240, 0); -webkit-text-stroke: 2px #FF6900;"></i>
    <% end %>
  <% end %>
<% end %>

app/views/experiences/_new_experience_form.html.erb
  <%# <%= link_to profile_page_path(current_user.username) do %>
    <%# <%= image_tag("go_back_icon.svg") %>
  <%# <% end %>
  <div class="feed-wall-title add-margin ">
  <h2>Share your Experience</h2>
  <hr>
</div>

<div class="container-experience">
  <%= simple_form_for [ @journey, @experience ] do |f| %>
    <%= f.input :title, label: 'Name of the experience', placeholder: "What did you do?", class: "input-journey-size" %>
    <%= f.input :content, label: 'Give us a description', placeholder: "How was it?" %>
    <%= f.input :category, :collection => ["Food", "Nightlife", "Art and Culture", "Other"], prompt: "Please select a category" %>
    <%= f.input :address, label: "Give us the address", placeholder: "Eg. Shoreditch Stables, London" %>
    <%= f.input :photos, label: "Pics or didn't happen...", as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, "Share", class: "btn-primary-custom new-journey-submit" %>
  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="feed-wall-title">
  <h2>Explore experiences</h2>
  <hr>
</div>

<div class="row m-1">
  <div class="col-12 my-3">
    <%= render 'shared/search', url: experiences_path %>
  </div>
  <div class="container">
    <div class="cards">
      <% @experiences.each do |experience| %>
        <div data-controller="saved-experience">
          <div class="photo", style="background-image: url(<%= cl_image_path experience.photos.first.key%>);">
           <div class="background-linear-gradient">
              <div class="thisclass">
                <div class="d-flex">
                  <div class="avatar m-3">
                    <%= link_to profile_page_path(experience.journey.user.username) do %>
                      <%= cl_image_tag experience.journey.user.photo.key, crop: :fill, alt: "profile-pic", class: "avatar" %>
                    <% end %>
                  </div>
                  <p class="username">
                    <%= link_to experience.journey.user.username, profile_page_path(experience.journey.user.username) %>
                  </p>
                </div>
                <%# dropdown for journeys %>
                <div class="d-flex flex-column justify-content-center parent-postion ">
                  <a data-saved-experience-target="button" class="plus-icon" data-action="click->saved-experience#dropdown"><%= image_tag("plus_icon.svg") %></a>
                  <div class="d-none form-position " data-saved-experience-target="form">
                    <%= simple_form_for @saved_experience, url: saved_experience_path(experience) do |f| %>
                    <%= f.input :journey, collection: current_user.journeys, label_method: :location, value_method: :id %>
                    <%= f.submit 'Add', class: "btn-primary-custom", style:"margin-left:146px;" %>
                    <% end %>
                  </div>
                </div>

              </div>

              <div class="title-likes">
                <div class="title">
                  <div class="d-flex flex-column address-margin">
                    <h3><%= experience.title %></h3>
                    <em><p class="m-0 address-color"><%= experience.address %></p></em>
                  </div>
                  <div data-controller="like-experience" data-like-experience-id-value="<%= experience.id %>" class="like-and-heart">
                    <div data-action="click->like-experience#updateLikes" data-like-experience-target = "likes" >
                      <%= render "experiences/like_link", journey: experience.journey, experience: experience %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
            <div class="content d-flex justify-content-between" data-controller="truncate-text">
              <div class="d-flex flex-column">
                <p class="d-inline-block text-truncate" data-truncate-text-target="textToTruncate"><strong><%= experience.journey.user.username %>: </strong><%= experience.content %></p>
                <%= image_tag "drop_down_icon.svg", class: "align-self-center username-content", data: { action: "click->truncate-text#truncateText" } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container-for-form-position background-off-white-gradient">
  <%= render "new_experience_form", experience: @experience %>
</div>