config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "pages#home"

  resources :users, only: %i[index]


  get "experiences/:id/like", to: "experiences#like", as: :like_experience

  get "up" => "rails/health#show", as: :rails_health_check

  get "/experiences", to: "experiences#index", as: :experiences

  resources :journeys, only: %i[show new create] do
    resources :experiences, only: %i[new create]
  end

  patch "/journeys/:id/delete_packing_item", to: "journeys#delete_packing_item", as: :delete_packing_item
  # resources :experiences, only: [:show] do
  #   member do
  #     patch "like", to: "experiences#like"
  #   end
  # end

  post "saved_experience/:experience_id", to: "saved_experiences#create", as: :saved_experience

  delete "/saved_experience/:id", to: "saved_experiences#destroy", as: :delete_saved_experience



  resources :chatrooms, only: %i[index show create] do
    resources :messages, only: :create
  end

  get "/:username", to: "users#profile_page", as: :profile_page

end

app/models/journey.rb
class Journey < ApplicationRecord
  attr_accessor :packing_item

  belongs_to :user

  has_many :experiences, dependent: :destroy
  has_many :saved_experiences, dependent: :destroy
  attr_accessor :dates

  geocoded_by :location

  # Before seeding comment from line out till line 25 and once the seed is done put this back in
  after_create :prebuild_sightseeing_list

  def packing_list
    @packing_list ||= super.blank? ? set_packing_list : super
  end

  # User input validations
  validates :location, :category, :start_date, :end_date, presence: true
  validate :validate_city_name # TODO: ADD A FLASH ALERT

  # Category column validations
  # Validates that the Category is at most 2 words and no nums
  validates :category, format: { with: /\A(?:[^\d\s]+\s*){1,2}\z/ }
  validates :category, length: { maximum: 20 }

  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }

  validates :notes, length: { maximum: 70 }

  private

  # Checks if user input for location is an existing city
  def validate_city_name
    errors.add(:location, "is not a valid city...") unless Geocoder.search(location).any?
  end

  def set_packing_list
    client = OpenAI::Client.new
    chaptgpt_response = client.chat(parameters: {
      messages: [
        { role: "system", content: "Packing assistant" },
        { role: "user", content: "I am going to #{location}, on the #{start_date}
         and coming back on #{end_date} for #{category}.
         Help me write a packing a list with maximum 10 packing items.
         Separate each packing item with a comma and a space and write only the packing items,
         do not write any pleasantries or extra information. Also write all of the items as a single string,
         do not categorise and do not number." }
      ],
      model: "gpt-3.5-turbo"
    })
    new_packing_list = chaptgpt_response["choices"][0]["message"]["content"].split(", ")
    update(packing_list: new_packing_list)
    @packing_list = new_packing_list
  end

  def prebuild_sightseeing_list
    location = self.location
    # Use with geocoder
    # experience.address.near(self.location)
    experience_in_location = Experience.all.select do |experience|
      experience.journey.location == location
    end

    experiences_top_most_liked = experience_in_location.sort_by(&:cached_weighted_average).reverse.first(5)

    experiences_top_most_liked.each { |experience| SavedExperience.create!(experience: experience, journey: self) }
  end
end

app/controllers/journeys_controller.rb
require "json"
require "open-uri"
require "net/http"

class JourneysController < ApplicationController
  before_action :set_journey, only: %i[show update delete_packing_item]

  def show
    # This is the api call to display the current weather
    weather = openweather_api_call
    country_code = weather['sys']['country']
    currency_and_language = big_data_api_call(country_code)

    # This gets all the data we are displaying in the show
    data_setter(weather, currency_and_language)

    # This will display the markers on the map
    experiences = @sight_seeing_list.map { |saved_experience| saved_experience.experience }
    mapbox_building(experiences)
  end

  def new
    @journey = Journey.new
  end

  def create
    @journey = Journey.new(journey_params)
    @journey.user = current_user
    if @journey.save!
      redirect_to journey_path(@journey)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @packing_list = @journey.packing_list << params[:journey][:packing_item]
    @packing_item = params[:journey][:packing_item]
    @journey.update(packing_list: @packing_list)

    respond_to do |format|
      format.html { redirect_to journey_path(@journey) }
      format.json # Follows the classic Rails flow and look for a create.json view
    end
  end

  def delete_packing_item
    @journey.packing_list.delete_at(params[:packingItem].to_i)
    @journey.save!
  end

  private

  # From this call we get weather temperature, an icon of current weather in destiation, time zone and country code
  def openweather_api_call
    serialized_weather = URI("https://api.openweathermap.org/data/2.5/weather?q=#{@journey.location}&appid=#{ENV['OPEN_WEATHER_API_KEY']}&units=metric")
    JSON.parse(Net::HTTP.get(serialized_weather))
  end

  # From this api call we get language and currency
  def big_data_api_call(country_code)
    uri_big_data = URI("https://api-bdc.net/data/country-info?code=#{country_code}&localityLanguage=en&key=#{ENV['BIG_DATA_API_KEY']}")
    JSON.parse(Net::HTTP.get(uri_big_data))
  end

  def data_setter(weather, currency_and_language)
    # Displays language
    @journey.language = currency_and_language['isoAdminLanguages'].first['isoName']

    # Displays currency
    @journey.currency = currency_and_language['currency']['code']

    # Sets the correct experiences
    @sight_seeing_list = @journey.saved_experiences

    # Gets the temparature
    @temperature_for_journey = weather["main"]["temp"]

    # Gets the icon for weather
    icon_id = weather['weather'].last['icon']
    @current_weather_icon_path = "https://openweathermap.org/img/w/#{icon_id}.png"

    # Gets time zone
    utc_offset_seconds = weather['timezone']
    @current_time_in_location = get_time_zone_identifier_by_utc_offset(utc_offset_seconds)
  end

  # Makes the markers for the map
  def mapbox_building(experiences_to_display)
    @markers = experiences_to_display.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        experience_popup_html: render_to_string(partial: "experience_popup", locals: { experience: experience }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  # Gets the time zone identifier by the UTC offset
  def get_time_zone_identifier_by_utc_offset(utc_offset_seconds)
    time_zone = ActiveSupport::TimeZone.all.find { |tz| tz.utc_offset == utc_offset_seconds }
    time_zone.formatted_offset
  end

  def set_journey
    @journey = Journey.find(params[:id])
  end

  def journey_params
    params.require(:journey).permit(:location, :start_date, :end_date, :category, :notes, :user, :packing_item)
  end
end

app/views/journeys/_experience_popup.html.erb
<div class="text-center" style="width:100px;height:140px;">
  <div class="popup-experience-photo-center">
    <%= cl_image_tag(experience.photos.first.key, :class => "popup-experience-photo-center") %>
  </div>

  <div class="d-flex flex-column">
    <p class="popup-title"><%= experience.title %></p>
    <p class="popup-address"><%= experience.address %></p>
  </div>
</div>

app/views/journeys/_marker.html.erb
<%= image_tag "map-pin.svg", height: 30, width: 30, alt: "Logo" %>

app/views/journeys/_new_journey_form.html.erb
<div class="feed-wall-title add-margin ">
  <h2>Add Journey</h2>
  <hr>
</div>

<div class="container-journey">
  <%= simple_form_for @journey, data: {controller: "datepicker"} do |f| %>
    <%= f.input :location,
                label: 'Where are you going?',
                placeholder: "Eg. London",
                class: "input-journey-size" %>
    <%= f.input :dates,
                label: "When are you going?",
                placeholder: "Please pick start and end date",
                input_html: { data: { datepicker_target: "dates" } } %>
    <%= f.input :start_date,
                as: :hidden,
                placeholder: "Please pick a start date",
                input_html: { data: { datepicker_target: "start" } } %>
    <%= f.input :end_date,
                as: :hidden,
                placeholder: "Please pick an end date",
                input_html: { data: { datepicker_target: "end" }, value: { } } %>
    <%= f.input :category, label: 'What will you be doing?', placeholder: "E.g. camping, hiking, city break..." %>
    <%= f.input :notes, placeholder: "Optional: My trip to berlin..." %>
    <%= f.button :submit, "Generate", class: "btn-primary-custom new-journey-submit" %>
  <% end %>
</div>

app/views/journeys/_packing_list_add_item.html.erb
<li class="packing-item py-2 px-2 d-flex justify-content-between packing<%= index %>" data-packing-list-target="packingItem">
  <%= packing_item.capitalize %>
  <div> <!-- add d-none -->
    <%= image_tag "minus_icon_orange.svg", class: "d-none packing#{index} #{index}", data: { packing_list_target: "minusIcon", action: "click->packing-list#delete" } %>
  </div>
</li>

app/views/journeys/new.html.erb
<div class="container-for-form-position background-off-white-gradient">
  <%= render "new_journey_form", journey: @journey %>
</div>

app/views/journeys/show.html.erb
<div class="show-container pb-3">
  <div class="d-flex px-3 pt-5">
    <%= link_to image_tag("go_back_icon.svg"), :back %>
    <div>
      <h2 class="location-title-bold my-0"><%= @journey.location %></h2>
      <p class="my-0 date-font-color"><%= @journey.start_date.strftime('%d/%m/%y') %> - <%= @journey.end_date.strftime('%d/%m/%y') %></p>
      <p class="top-experiences-for-location-italic"><em><%= @journey.notes %></em></p>
    </div>
    <% if @journey.user == current_user %>
      <div>
        <%= link_to new_journey_experience_path(@journey), class: "btn-primary-custom secondary-button-position", id: "share-button-show-page" do %>
          <%= image_tag("share_arrow_white.svg") %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-between container-basic-info-icon">
    <div class="d-flex flex-column justify-content-center">
      <!-- Displaying the current weather through an api -->
      <%= image_tag @current_weather_icon_path, class: "basic-info-icon my-2" %>
      <p class="basic-info-text-margin"><%= @temperature_for_journey %>°C</p>
    </div>

    <div class="d-flex flex-column text-centre">
      <!-- Displaying the languange -->
      <%= image_tag "globe_icon.svg", class: "basic-info-icon my-2" %>
      <p class="basic-info-text-margin"><%= @journey.language %></p>
    </div>

    <div class="d-flex flex-column">
      <!-- Displaying the currency -->
      <%= image_tag "currency_icon.svg", class: "basic-info-icon my-2" %>
      <p class="basic-info-text-margin"><%= @journey.currency %></p>
    </div>

    <div class="d-flex flex-column">
      <!-- Displaying the currency -->
      <%= image_tag "time_zone_icon.svg", class: "basic-info-icon my-2" %>
      <%# need to give the correct timme zone %>
      <p class="basic-info-text-margin">GMT <%= @current_time_in_location %></p>
    </div>
  </div>

  <div class="list my-4"
  data-controller="dropdown-lists packing-list"
  data-packing-list-journey-value="<%= @journey.id %>"> <!-- stimulus controllers -->
    <div class="d-flex justify-content-between">
      <div class="d-flex">
        <%= image_tag "laguage.svg", class: "list-icon" %>
        <h2 class="align-self-center list-title">Packing</h2>
      </div>
      <%# if it breaks add to the div below %>
      <%# data-action="click->dropdown-lists#dropdown"
           data-action="click->packing-lists#hideDeleteButtons" %>
      <div
           data-dropdown-lists-target="dropdown-lists"
           data-packing-list-target="packing-list"
      > <!-- data action-->
      <% if @journey.user == current_user %>
        <%= image_tag "pencil_icon_grey.svg", data: { packing_list_target: "trash", action: "click->packing-list#hideDeleteButtons" } %>
      <% end %>
        <%= image_tag "drop_down_icon.svg", class: "dropdown-icon-size", data: { dropdown_lists_target: "icon", action: "click->dropdown-lists#dropdown" } %>
      </div>
    </div>
    <div data-dropdown-lists-target="list">
      <ul class="mt-3 packing-list-ul"
          data-packing-list-target="items">
        <% @journey.packing_list.each_with_index do |packing_item, index| %>
          <%= render "packing_list_add_item", packing_item: packing_item, index: index %>
        <% end %>
      </ul>
      <% if @journey.user == current_user %>
        <div>
          <%= simple_form_for @journey, data: {
            packing_list_target: "form",
            action: "submit->packing-list#send"
          } do |f| %>
            <%= f.input :packing_item, placeholder: "What are you forgetting?", label_html: {class: "d-none"} %>
            <%= f.submit 'Add', class: "btn-secondary-custom", id: "button" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>


  <div class="list" data-controller="dropdown-lists"> <!-- stimulus controller -->
    <div class="d-flex justify-content-between">
      <div class="d-flex">
        <%= image_tag "diamond_icon.svg", class: "list-icon"%>
        <h2 class="align-self-center list-title">Sightseeing</h2>
      </div>
      <div data-action="click->dropdown-lists#dropdown" data-dropdown-lists-target="dropdown-lists">
        <%= image_tag "drop_down_icon.svg", class: "dropdown-icon-size", data: { dropdown_lists_target: "icon" }  %>
      </div>
    </div>
    <div data-dropdown-lists-target="list">
      <div>
        <p class="top-experiences-for-location-italic my-2"><em>Top experiences people had in <%= @journey.location %></em></p>
        <div class="experience-card w-100 p-2 map-container">
          <div id="map"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
      <% @sight_seeing_list.each do |saved_experience| %>
        <div class="experience-card mt-3">
          <div class="d-flex flex-column">
            <div class="p-2 parent-position-relative">
              <%= link_to delete_saved_experience_path(saved_experience), data: { turbo_method: :delete }, class: "destroy-link-position" do %>
                <% if @journey.user == current_user %>
                  <%= image_tag "minus_icon.svg" %>
                <% end %>
              <% end %>
              <%= cl_image_tag saved_experience.experience.photos.first.key, class: "experiences-photo-size" %>
            </div>
            <div class="text-experience-card-margin-left">
              <h3 class="mt-2 mx-2"><%= saved_experience.experience.title %></h3>
              <p class="mt-0 mx-2 mb-2"><%= saved_experience.experience.address %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>